### ISSUE TITLE
BIND import fails with key error

### ISSUE THREAD

**Issue by fnordpojk** [operasoftware/dns-ui#15] opened 2017-08-07 15:03 UTC
Trying to import a bog standard BIND zone file, the import fails after selecting records with:

The zone update failed. The following error message was given: Key 'name' not present or not a String

Google suggests this is because the API changed regarding how you need to specify the name property in your API call.

pdns 4.0.4, dns-ui master. Issue was the same with pdns master.

**Comment by thomasp-opera** [comment] 2017-08-08 09:45
Hi, thanks for your bug report. Could you provide an example file that triggers this error please?

**Comment by fnordpojk** [comment] 2017-08-08 13:05
I have emailed it to you since I don't want it publicly indexed. :)

**Comment by thomasp-opera** [comment] 2017-08-08 13:22
Thank you, I am able to reproduce the problem with the file you have provided. It appears to be a bug in the bind file parser (if you check the update preview you can see that the first two records are parsed as ending in `..`). I'll try to get you a fix for this soon.

**Comment by fnordpojk** [comment] 2017-08-08 13:35
Excellent, thank you. Please let me know if I can be of any assistance.

**Closed** 2017-08-08 14:42 UTC

**Comment by thomasp-opera** [comment] 2017-08-08 14:44
It was due to incorrect canonicalization of zone names under `$ORIGIN .`. Fixed on master and tests added.
